### ISSUE TITLE
script2.test.js

### ISSUE THREAD

**Issue by bryanleejh** [aneagoie/udemy-testing-exercise#1]
Hey man is the script2.test.js working?

Seem to have issues with the node fetch.

FetchError: invalid json response body at https://swapi.co/api/people reason: Unexpected token < in JSON at position 0

      14 | const getPeople = async(fetch) => {
      15 |   const getRequest = await fetch('https://swapi.co/api/people');
    > 16 |   const data =  await getRequest.json();
         |                 ^
      17 |   console.log(data);
      18 | 
      19 |   return {

      at node_modules/node-fetch/lib/index.js:272:32
      at Object.getPeople (script2.js:16:17)

  ● calls swapi to get people

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

       8 |   //code, in order to make sure that assertions in a
       9 |   //callback actually got called.
    > 10 |   expect.assertions(1)
         |          ^
      11 |   return swapi.getPeople(fetch).then(data => {
      12 |     expect(data.count).toEqual(87);
      13 |   })

      at Object.<anonymous> (script2.test.js:10:10)

  ● calls swapi to get people with promise

    FetchError: invalid json response body at https://swapi.co/api/people reason: Unexpected token < in JSON at position 0

      at node_modules/node-fetch/lib/index.js:272:32

  ● calls swapi to get people with promise

    expect.assertions(2)

    Expected two assertions to be called but received zero assertion calls.

      15 | 
      16 | it('calls swapi to get people with promise', () => {
    > 17 |   expect.assertions(2)
         |          ^
      18 |   return swapi.getPeoplePromise(fetch).then(data => {
      19 |     expect(data.count).toEqual(87);
      20 |     expect(data.results.length).toBeGreaterThan(5);

      at Object.<anonymous> (script2.test.js:17:10)

**Comment by bryanleejh** [comment]
Thanks Andre!
